services:
  fflogbot:
    build:
      context: ./build/docker/
      dockerfile: Dockerfile
    image: fapbeast/docker-pilot:fflogbot-v${version}
    container_name: fflogbot-v${version}
    env_file:
      - .env